# Generated by Django 5.2.4 on 2025-08-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subscription_type', models.CharField(choices=[('email', 'Newsletter Email'), ('whatsapp', 'Abonnement WhatsApp'), ('both', 'Email et WhatsApp')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('receive_promotions', models.BooleanField(default=True)),
                ('receive_new_products', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
